### ISSUE TITLE
Driving motor and servo motor detection

### ISSUE THREAD

**Issue by sparacios** [U-K-L/autonomous_rover#11]
The issue is that we need some time of structure that can help us determine the id of there motor and what state is set to the motor. The states are definite and not recommended to change during run time. The design i implemented was to ease that however it needs further exploration because the design i implemented was just to tackle the problem of access. Yes it can determine the state of each servo however the state cannot be change. That is not proper and will need some redesigning

**Comment by U-K-L** [comment]
I have seen the code you proposed. How does this fix this issue, can you be a little more specific?

**Comment by sparacios** [comment]
Update, The classes written for the drivetrain code is complete and the state issue is resolved so that i can replicate previous movement variations. Just need to add distance based movement
